### ISSUE TITLE
Zazu can't start

### ISSUE THREAD

**Issue by unpeudetout** [tinytacoteam/zazu#280]
Zazu can't start, sorry for my english ^^
### Expected Behavior
Starting Zazu correctly
### Actual Behavior
Full crash, a message appeared
![screenshot_256](https://cloud.githubusercontent.com/assets/13904910/24321146/7f6b17be-1145-11e7-801a-e5a59f11fbc5.png)

### Steps to reproduce the behavior
Install Zazu and launch it
### Versions

* Zazu: 0.5.1
* OS: Windows 10
* GIT:

Please, include a link to gist of most applicable `~/.zazu/log/` file.

[zazu.log.2017-03-24.txt](https://github.com/tinytacoteam/zazu/files/869887/zazu.log.2017-03-24.txt)

**Comment by blainesch** [comment]
Thank you for reporting!

**Comment by danielbayerlein** [comment]
#275

**Comment by danielbayerlein** [comment]
Should be fixed with v0.5.2

**Comment by blainesch** [comment]
Thanks for updating the ticket @danielbayerlein !! :D

**Comment by unpeudetout** [comment]
Yes, it's fixed in v0.5.2
