### ISSUE TITLE
Zazu won't start after update

### ISSUE THREAD

**Issue by luiscachog** [tinytacoteam/zazu#347]
### Expected Behavior
Zazu starts normally
### Actual Behavior
/opt/Zazu/zazu
/opt/Zazu/zazu[25056]: ../../third_party/electron_node/src/node_contextify.cc:640:static void node::contextify::ContextifyScript::New(const FunctionCallbackInfo<v8::Value> &): Assertion `args[1]->IsString()' failed.
 1: 0x55c8860c1655 node::Abort() [/opt/Zazu/zazu]
 2: 0x55c8860c0f1f  [/opt/Zazu/zazu]
 3: 0x55c8860bc081  [/opt/Zazu/zazu]
 4: 0x55c8823dc4c7  [/opt/Zazu/zazu]
 5: 0x55c88239df0e  [/opt/Zazu/zazu]
 6: 0x55c88239d828  [/opt/Zazu/zazu]
 7: 0x55c882b97f0b  [/opt/Zazu/zazu]
[1]    25056 abort      /opt/Zazu/zazu

### Steps to reproduce the behavior
dpkg -i zazu_0.6.0_amd64.deb
/opt/Zazu/zazu
### Versions

* Zazu: 0.6.0
* OS: Linux Mint x86_64
* GIT: 2.22.0

Please, include a link to gist of most applicable `~/.zazu/log/` file.
https://gist.github.com/k4ch0/e48c538a851294f6a2f6142f22482822

**Comment by linonetwo** [comment]
I'm going to download a virtualbox to test out.

---
I've tried in latest Ubuntu, it works fine. (running `/usr/local/bin/zazu` is not working, click its icon in launcher is fine). I'm going to try in Mint.

**Comment by linonetwo** [comment]
Could you try to rebuild manually? This deb is generated in an Ubuntu CI, I don't know what could cause this error in Mint.

I will look into this next weekend, for this week I'm spending time with node-solid-server and react-three-fiber and encompass-ecs.

**Comment by linoskoczek** [comment]
I've just installed it on my Mint 18.3 sylvia x86_64 and it works correctly.

**Comment by linonetwo** [comment]
@linoskoczek So, how did you installed? Maybe it is the installation procedure that made the difference.

**Comment by luiscachog** [comment]
Sorry for the long wait, I do reinstall version 6 but before I cleanup all my previous configuration, I delete the files on:

```
sudo apt purge zazu
~/.config/zazu
~/.zazu
~/.zazurc.json
```
After that I reinstalled zazu:
```
sudo dpkg -i zazu_0.6.0_amd64.deb
``` 

And it is working now.

Thank you
