### ISSUE TITLE
Result items don't match what i type on macOS

### ISSUE THREAD

**Issue by acbetter** [tinytacoteam/zazu#351]
### Expected Behavior

![image](https://user-images.githubusercontent.com/13360124/61201518-5c87c980-a717-11e9-9559-8ff353f13e6d.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/13360124/61199432-87baea80-a710-11e9-8b01-0b494044a155.png)

### Steps to reproduce the behavior

Toggle Zazu on and type "term".

### Versions

* App Environment: production
* App Version: 0.6.0
* Electron Version: 5.0.4
* Node Version: 12.0.0
* Chrome Version: 73.0.3683.121
* OS: macOS 10.14.5

### Log

[zazu.log.2019-07-15.zip](https://github.com/tinytacoteam/zazu/files/3391269/zazu.log.2019-07-15.zip)

**Comment by linonetwo** [comment]
Are these results from plugin `zazu-file-finder`? I personally don't use this, because I feel Mac launchpad convenient.

But I will look into it, maybe next weekend.

**Comment by acbetter** [comment]
> Are these results from plugin `zazu-file-finder`? I personally don't use this, because I feel Mac launchpad convenient.
> 
> But I will look into it, maybe next weekend.

Ye, seems from `zazu-file-finder`. Here's my settings file.

```json
{
  "hotkey": "cmd+space",
  "theme": "Eric-Jackson/zazu-clement-theme",
  "displayOn": "detect",
  "plugins": [
    "tinytacoteam/zazu-calculator",
    "tinytacoteam/zazu-file-finder",
    "tinytacoteam/zazu-template",
    "tinytacoteam/zazu-system",
    "tinytacoteam/zazu-package-manager",
    {
      "name": "tinytacoteam/zazu-fallback",
      "variables": {
        "rootSearches": ["google"]
      }
    },
    {
      "name": "tinytacoteam/zazu-clipboard",
      "variables": {
        "ClipboardKey": "cmd+shift+v"
      }
    }
  ]
}
```

**Comment by acbetter** [comment]
The plugin `zazu-file-finder` used a module named `fuzzyfind` but I perfer `string contain`. Maybe can add one setting item something like:

```json
{
  "hotkey": "cmd+space",
  "theme": "Eric-Jackson/zazu-clement-theme",
  "displayOn": "detect",
  "plugins": [
    "tinytacoteam/zazu-file-finder",
    {
      "name": "inytacoteam/zazu-file-finder",
      "variables": {
        "MatchingAlgorithm": "fuzzyfind", # or "stringcontain"
      }
    }
  ]
}
```

**Comment by linonetwo** [comment]
Ok, I will add it now.

**Comment by linonetwo** [comment]
It should be working now, update your plugin and config it:

```
{
      "name": "tinytacoteam/zazu-file-finder",
      "variables": {
        "matchBy": "stringincludes"
      }
    }
```

**Comment by acbetter** [comment]
After i deleted old plugin `zazu-file-finder` and installed a new one, it worked!!! Thanks very much!

**Comment by acbetter** [comment]
If you have a "Uncaught Exception" after updated to version 1.1.0 on macOS, here's [Resolution](https://github.com/tinytacoteam/zazu-file-finder/issues/44)

![image](https://user-images.githubusercontent.com/13360124/61213266-21958e00-a737-11e9-98c6-1ebc3eec172a.png)
